app/urls.py
from django.urls import path
from app import views

app_name='raina'

urlpatterns=[
    path('h3/',views.h3,name='h3'),
]

project7/urls.py
from django.contrib import admin
from django.urls import path,include

from app import views# imported only views module from app package

import app# importing total app package

urlpatterns = [
    path('admin/', admin.site.urls),
    path('h1/',views.h1,name='h1'),
    path('h2/',views.h2,name='h2'),
    path('h4/',views.h4,name='h4'),
    path('app/',include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def h1(request):
    d={'name':'Baba Chari'}
    return render(request,'h1.html',d)# giving context is optional

def h2(request):
    return render(request,'h2.html')


def h3(request):
    return render(request,'h3.html')

def h4(request):
    return render(request,'h4.html',context={'a':10000,'b':1000})

templates/h1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>h1.html file</title>
</head>
<body>
    <h1>This is h1.html file</h1>

    <h1>Welcome Mr/Ms {{name}}</h1>

    <a href="{% url 'h2' %}">click on this to go to h2.html file</a><br>

    <a href="{% url 'raina:h3' %}">click on this to go to h3.html</a>
</body>
</html>

templates/h2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is H2.html file</h1>

    <a href="{% url 'h1' %}">click on this to go to h1.html</a>
</body>
</html>

templates/h3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This h3.html file</h1>
</body>
</html>

templates/h4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is h4.html</h1>
    <h1>This Demonstration of if by jinja</h1>
<!--
    {% if a > b %}
        <h1>inside if condtion</h1>
        <h1>{{a}}</h1>
    {% endif %}
-->
<!--
{% if a > b %}
    <h1>inside if block </h1>
    {{a}}
{% else %}
    <h1>inside else block </h1>
    {{b}}
{% endif %}
-->

{% if a > b %}
    <h1>a is greater value</h1>
{% elif b > a %}
    <h1>b is greater value</h1>
{% else %}
    <h1>values are same </h1>
{% endif %}




</body>
</html>